
spring:
  application:
    name: gupao-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411/


server:
  port: 8084